version: '3.8'

services:
  botfuria: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    container_name: botfuria-app
    networks:
      - app_network


networks:
  app_network:
    driver: bridge